apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    kustomize.component: metacontroller
namespace: kubeflow
resources:
- cluster-role.yaml
- cluster-role-binding.yaml
- crd.yaml
- service-account.yaml
- stateful-set.yaml
