apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- files:
  - sync.py
  name: kubeflow-pipelines-profile-controller-code
- envs:
  - params.env
  name: kubeflow-pipelines-profile-controller-env
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app: kubeflow-pipelines-profile-controller
namespace: kubeflow
resources:
- service.yaml
- deployment.yaml
- decorator-controller.yaml
