apiVersion: kustomize.config.k8s.io/v1beta1
configurations:
- params.yaml
kind: Kustomization
patches:
- path: workflow-controller-deployment-patch.yaml
- path: workflow-controller-configmap-patch.yaml
resources:
- ../upstream/manifests/base/workflow-controller
