apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: workflow-controller-clusterrolebinding-patch.json
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: argo-binding
    version: v1
resources:
- ../../upstream/manifests/base/crds
- ../../upstream/manifests/cluster-install/workflow-controller-rbac
- ../../base
