apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: ghcr.io/kubeflow/kfp-cache-deployer
  newTag: 2.5.0
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app: cache-deployer
resources:
- cache-deployer-role.yaml
- cache-deployer-rolebinding.yaml
- cache-deployer-deployment.yaml
