apiVersion: kustomize.config.k8s.io/v1beta1
configurations:
- params.yaml
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app: cache-server-cert-manager
namespace: kubeflow
resources:
- cache-cert-issuer.yaml
- cache-cert.yaml
- cache-webhook-config.yaml
