apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: ghcr.io/kubeflow/kfp-metadata-writer
  newTag: 2.5.0
kind: Kustomization
resources:
- metadata-writer-deployment.yaml
- metadata-writer-role.yaml
- metadata-writer-rolebinding.yaml
- metadata-writer-sa.yaml
